### ISSUE TITLE
Python Indentation

### ISSUE THREAD

**Issue by patrikarlos** [Jhansidunuka/track-a-mac#1]
ubuntu@instance-dunukajhansi:~$ ./backend
  File "./backend", line 97
    connection.commit()
                      ^
TabError: inconsistent use of tabs and spaces in indentation
ubuntu@instance-dunukajhansi:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
ubuntu@instance-dunukajhansi:~$

**Comment by patrikarlos** [comment]
View the 'raw' text, formatting corrupts it.

**Comment by Jhansidunuka** [comment]
Hi Patrik,
I hope you are having a good day.

I have installed the lsb release package already. I am not clear with your
comment. Is there an issue with the indentation? and what do you mean by
issue with the git repo? Hoping to hear from you.

Thank you,
BR,
Jhansi Dunuka

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by patrikarlos** [comment]
Yes, the program does not run, because of that error. 
I just included the lsb_release output to show what the system is running on.

**Comment by Jhansidunuka** [comment]
Okay. I will correct it and let you know. Thank you so much for informing.

Have a pleasant evening!

BR,
Jhansi Dunuka

**Comment by Jhansidunuka** [comment]
Hi Patrik,

Hoping you are fine.

I am writing to let you know that I have updated my git repo (backend).

Thanks and Regards,
Jhansi Dunuka

**Comment by patrikarlos** [comment]
Done
